// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_XzqLgj4Fk_Ee4J9zCZfOQtoThN-vim0',
    appId: '1:562121305021:web:37d26867e2b8d131f100d4',
    messagingSenderId: '562121305021',
    projectId: 'travelaca-37958',
    authDomain: 'travelaca-37958.firebaseapp.com',
    storageBucket: 'travelaca-37958.firebasestorage.app',
    measurementId: 'G-MNHQ1E5LCK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLBRdEpSuWS6bmCtyUJ8wWLToc7ORd0tw',
    appId: '1:562121305021:ios:8702105f8ab8b88ef100d4',
    messagingSenderId: '562121305021',
    projectId: 'travelaca-37958',
    storageBucket: 'travelaca-37958.firebasestorage.app',
    iosBundleId: 'com.example.travelaca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLBRdEpSuWS6bmCtyUJ8wWLToc7ORd0tw',
    appId: '1:562121305021:ios:8702105f8ab8b88ef100d4',
    messagingSenderId: '562121305021',
    projectId: 'travelaca-37958',
    storageBucket: 'travelaca-37958.firebasestorage.app',
    iosBundleId: 'com.example.travelaca',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs9dTTyrbGNrpOlYC-Vcb-5CED2_B2GVE',
    appId: '1:562121305021:android:b818633cddf87d0df100d4',
    messagingSenderId: '562121305021',
    projectId: 'travelaca-37958',
    storageBucket: 'travelaca-37958.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_XzqLgj4Fk_Ee4J9zCZfOQtoThN-vim0',
    appId: '1:562121305021:web:533719f076b1929ef100d4',
    messagingSenderId: '562121305021',
    projectId: 'travelaca-37958',
    authDomain: 'travelaca-37958.firebaseapp.com',
    storageBucket: 'travelaca-37958.firebasestorage.app',
    measurementId: 'G-4DY85GRD3Z',
  );

}